language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kwgurney/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kwgurney/docker-react npm run test

